### ISSUE TITLE
Y3: Task Group: Generalist Repositories as Institutional Repositories Use Cases

### ISSUE THREAD

**Issue by saragon02** [NIH-GREI/grei-pm#110]
## Link to Deliverables in Zenodo and Blog:
- [Use Cases for Generalist Repositories](https://zenodo.org/communities/grei/records?q=Use%20Cases_&l=list&p=1&s=10&sort=bestmatch)
- [Blog](https://medium.com/@blog-grei/generalist-repositories-update-use-case-catalog-to-describe-institutional-data-sharing-support-e2fdbc65332a)

## Objective:
- https://github.com/NIH-GREI/grei-pm/issues/12 

## Tasks:
- #93 

## Deliverables:
- #99 
- #112 

## Steps to completion:
- [x] Task group has followed [Procedures for Forming a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780045)
- [x] Task group has read and followed [Procedures for Facilitating a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780532)
- [x] Task(s) completed
- [x] Deliverable(s) completed
- [x] Reviewed by CWG committee (if applicable)
- [x] Uploaded to Zenodo
- [x] Blog and/or webinar
- [x] Task group has read and followed [Procedures for Sunsetting a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245781023)

## Group Co-Leads and contact:
- Ana Van Gulick: ana@figshare.com
- Sara Gonzales: sara.gonzales2@northwestern.edu

## Members and Repositories:
- Jen Gibson (Dryad)
- Matt Carson (Zenodo)
- Pearl Go (Zenodo)
- Gretchen Gueguen (OSF)
- Eric Olson (OSF)
- Sarah Sweet (Vivli)
- Gustavo Durand (Dataverse)
- Traci Snowden (Mendeley)
- Lisa Curtin (Figshare)

## Related
- #12

## Resources

- [FASEB-Choosing Your Generalist Repository](https://dataworks.faseb.org/helpdesk/kb/choosing-a-generalist-repository)
