### ISSUE TITLE
Y3: Co-Chairs Sync with Community Engagement

### ISSUE THREAD

**Issue by lekshmi-sheelakumari** [NIH-GREI/grei-pm#114]
## Objective 
A monthly sync between GREI Y3 Co-Chairs and 
## Related Issues 

- https://github.com/NIH-GREI/grei-pm/issues/79

## Tasks 
- [x] @traciasnowden  to email the leads- with the objectives of this sync between Co-Chairs and Comm Engagement (05/16)
- [x] @lekshmi-sheelakumari to send a Poll after this to decide on the timings (05/16)
- [ ] First Meeting Scheduled on 21st June

## Agenda and Meeting Notes 

- [Community Engagement (CE) Running Meeting Notes [GREI]](https://docs.google.com/document/d/1eyjwBOm6ICZoNLkayohnSRjEWcxfRDdCHruWIk7lsfI/edit?pli=1)

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
