### ISSUE TITLE
Y3: GREI Y3 Deliverables- Champions

### ISSUE THREAD

**Issue by lekshmi-sheelakumari** [NIH-GREI/grei-pm#116]
##Deliverable
[GREI Y3 Task Groups & Deliverables](https://docs.google.com/spreadsheets/d/1khSF8hSIMl-QjBFozqj3udV5tNXuGO6_3Le0l9-Nq-A/edit?gid=329628314#gid=329628314)

## Objective
To ensure that all repositories have equitable opportunity to own and lead Y3 Plan tasks and deliverables Co-Chairs are asking that PIs take a look at the [GREI Y3 Deliverables- Champions](https://docs.google.com/spreadsheets/d/1khSF8hSIMl-QjBFozqj3udV5tNXuGO6_3Le0l9-Nq-A/edit#gid=1300563565) and nominate “Y3 Champion(s)” from their repository.   

## Tasks
- [x] @kristiholmes to update the format to capture the areas of interest
- [x] @lekshmi-sheelakumari to send a reminder to team to nominate GREI Champions before 15th May
- [x] Discussed and added leads and co-leads to Task Groups- to be confirmed with the nominees by individuals mentioned in comments. (ACTION)- By June 14
- [x] Create a timeline based view of the Task Groups, with a heat map for prioritizing the Task Groups, and Co-chairs mapped to these task groups - [TG timing/dependencies](https://docs.google.com/spreadsheets/d/1khSF8hSIMl-QjBFozqj3udV5tNXuGO6_3Le0l9-Nq-A/edit?pli=1&gid=329628314#gid=329628314)
- [x] Community Engagement Task Groups to be updated, OSF nominations to be added. (Lekshmi to complete)
- [x] GitHub Issues related to the Task Groups to be linked in the Champions Nominees list 
- [x] @sbarbosadataverse to assign the Task Group leads to Task Group GitHub Issues to update the details
- [x] Review messaging to the TG leads in the [GREI Y3 Deliverables- Champions](https://docs.google.com/spreadsheets/d/1khSF8hSIMl-QjBFozqj3udV5tNXuGO6_3Le0l9-Nq-A/edit?pli=1&gid=1021412685#gid=1021412685)- [Draft instructions to TG Leads](https://docs.google.com/document/d/1zTHzr-oSy20BSdUMTxbAjYDES6i_87PYs0HfrORjUSw/edit)

## Deliverables

- [x] Completed list of Y3 CWG Deliverables
- [x] GREI Task Groups- Nominations for Leads/Co-leads

## Resources
- [GREI Y3 Deliverables- Champions](https://docs.google.com/spreadsheets/d/1khSF8hSIMl-QjBFozqj3udV5tNXuGO6_3Le0l9-Nq-A/edit#gid=1300563565)
- [Task Group Nominations](https://docs.google.com/spreadsheets/d/1khSF8hSIMl-QjBFozqj3udV5tNXuGO6_3Le0l9-Nq-A/edit?pli=1&gid=1021412685#gid=1021412685)
- [TG timing/dependencies](https://docs.google.com/spreadsheets/d/1khSF8hSIMl-QjBFozqj3udV5tNXuGO6_3Le0l9-Nq-A/edit?pli=1&gid=329628314#gid=329628314)

## Related Issues
- #113
