### ISSUE TITLE
GREI-CE-Execution-Unit

### ISSUE THREAD

**Issue by lcurtin** [NIH-GREI/grei-pm#121]
## Objective
- #15 

### Community Engagement Execution Unit Responsibilities 
  - Liaise with Task Groups
  - Organize webinars
  - Manage GREI blog
  - Grow the GREI Google group and keep folks up to date
  - Facilitate and/or lead conference proposals & sessions

(Taken from [Community Engagement - 2023 GREI In-Person Subcommittee Retrospective](https://docs.google.com/presentation/d/1hbgdg3lM-hChWUvsnuBXjSOpVq3yw46-BU1khmYIObs/edit?usp=sharing))

## Task (Y3)
- #59 

## Deliverables (Y3)
- #63 
  - [x] Blog 1 - 2024-04-30 [Kicking Off GREI’s Third Year](https://medium.com/@blog-grei/kicking-off-greis-third-year-b8709ab45a48)
  - [x] Blog 2 - 2024-06-20 [Community Feedback Shapes the Future of Generalist Repositories: Insights from GREI Community Calls](https://medium.com/@blog-grei/community-feedback-shapes-the-future-of-generalist-repositories-insights-from-grei-community-calls-b431c583ad97)
  - [x] Blog 3 - 2024-07-29 [GREI Flowchart for Data Sharing Decisions](https://medium.com/@blog-grei/grei-flowchart-for-data-sharing-decisions-91d7eab08330)
  - [x] Blog 4 - 2024-08-05 [Generalist Repositories Update Use Case Catalog to Describe Institutional Data Sharing Support](https://medium.com/@blog-grei/e2fdbc65332a) 
  - [ ] Blog 5 - (Scheduled publication date: 2024-08-12) Empowering Global Progress: GREI Coopetition's Role in Standardizing Transparency, Community, and Sustainability Initiatives
  - [ ] Blog 6
  - [ ] Blog 7
  - [ ] Blog 8
  - [ ] Blog 9
  - [ ] Blog 10
  - [ ] Blog 11
  - [ ] Blog 12
- #64 
  - [x]  Webinar 1 - 2024-05-15 Data Sharing: Generalist Repository Ecosystem Initiative (NIH Library)
  - [x] Webinar 2 - 2024-05-23 Managing Research Data Across Multiple Data Repositories (FASEB DataWorks! Salon)
  - [ ] Webinar 3 - 2024-08-07 The NIH Generalist Repository Ecosystem Initiative (GREI): Supporting Data Sharing in Generalist Repositories (NNLM National Center for Data Services)
  - [ ] Webinar 4
  - [ ] Webinar 5
  - [ ] Webinar 6 
- #65 
- #66  

## Group Lead and contact:
- Lisa Curtin @lcurtin (lisa@figshare.com) - Figshare
 
## Members and Repositories:
- Dwayne Liburd (Dataverse)
- Jennifer Gibson (Dryad)
- Ana Van Gulick (Figshare)
- Shanthi Keethadevan (Mendeley Data)
- Amanda Staller (OSF)
- Julie Wood (Vivli)
- Pearl Go (Zenodo)

## Resources
- [Y3 Community Engagement](https://drive.google.com/drive/folders/1JhIYv3F1GEwBj5S1Mp7tXQBGTniZl-T2?usp=sharing) (Google Drive folder)
- [GREI Training & Outreach Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_daqo9596gcl56ebc6ni8k86j68@group.calendar.google.com&ctz=America/Los_Angeles)
- [GREI Community Blog](https://medium.com/@blog-grei)
- GREI Collaborative Webinars & Other Events - link to be added once ODSS site is updated

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
