### ISSUE TITLE
Y2-4: Task Group: Carpentries

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#123]
## Link to Deliverables in Zenodo:
- 

## Objective: (Which objective is this working group related to?)
- #15 

## Tasks: 

- [ ] Task 8.3: Collaboration with The Carpentries: Determine opportunities for alignment between the existing Carpentries community, current data-sharing best practices, and the needs of the GREI community. Discuss opportunities to  deliver Carpentries’ content in new formats.

## Deliverables:
If the issue already exists, link it above
If you need a new issue, create the issue here 

- [ ] Deliverable 8.3.1: Work with The Carpentries to determine the scope of the effort, isolating which data management best practices would be most beneficial to our shared communities. Areas of discussion will include FAIR data principles, data and software deposit best practices, and the use of generalist repositories. 
- [ ] Deliverable 8.3.2: Work with The Carpentries to determine which lessons to prioritize for exploration and future revisions. Up to three feedback opportunities (e.g., community call, GitHub conversation) with The Carpentries Maintainer community and Curriculum Advisory Committees will guide determining how to incorporate new material and best practices into The Carpentries' existing training pedagogy.
- [ ] Deliverable 8.3.3: The Carpentries will provide template resources for GREI to modify, refine, and adapt for training in topics supporting GREI repositories.
- [ ] Deliverable 8.3.4: Work with The Carpentries to facilitate discussions and feedback mechanisms (e.g., GitHub conversations) in alignment with its Community Development Program to ensure that GREI’s training meets the community's evolving needs, including researchers and librarians.
- [ ] Deliverable 8.3.5: Work with The Carpentries to define and measure the success of its training modules and workshops based on The Carpentries Theory of Change. 

## Steps to completion:
- [x] Task group has followed [Procedures for Forming a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780045)
- [x] Task group has read and followed [Procedures for Facilitating a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780532)
- [ ] Task(s) completed
- [ ] Deliverable(s) completed
- [ ] Reviewed by CWG committee (if applicable)
- [ ] Uploaded to Zenodo
- [ ] Blog and/or webinar
- [ ] Task group has read and followed [Procedures for Sunsetting a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245781023)

## Group Co-Leads and contact:
- Name, email, Gitaccount

## Members and Repositories:
- 

## Resources:
- [Task Group SOP Template-DRAFT](https://docs.google.com/document/d/185S-hvjIysh-a1k7iZPSUWxjQ4kfXG2AapPZkIw7QH8/edit#heading=h.tyus4hcbugou)

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
