### ISSUE TITLE
Y3-4: Task Group: Real-time metrics

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#125]
## Objective: 
- #11 

## Tasks:
- #103 

## Deliverables:
- #108 

## Steps to completion:
- [x] Task group has followed [Procedures for Forming a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780045)
- [ ] Task group has read and followed [Procedures for Facilitating a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780532)
- [ ] Task(s) completed
- [ ] Deliverable(s) completed
- [ ] Reviewed by CWG committee (if applicable)
- [ ] Uploaded to Zenodo
- [ ] Blog and/or webinar
- [ ] Task group has read and followed [Procedures for Sunsetting a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245781023)

## Group Co-Leads and contact:
Tina Zdawczyk and Traci Snowden (Co-Leads) 

## Members and Repositories:
- Iratxe Puebla
- Audrey Hamelers
- Mark Hahnel
- Eric Olson
- Brian Geiger
- Kristi Holmes
- Lars Holm Nielsen

### For Awareness Only:
- Ana Van Gulick

## Resources:
- [Task Group Google Drive Folder](https://drive.google.com/drive/folders/1BRCXoFXZd-xRIo7NcMnOYfWDxKwI1ZER?usp=drive_link)
- [Task Group Roster](https://docs.google.com/spreadsheets/d/1Ve0qaK1Gwb1sBLrFTg51O1EQgLapglNFcelP5Gd1ffU/edit?usp=drive_link) 
- [Task Group SOP](https://docs.google.com/document/d/1UXBMFJapum_Wl9OJ4S4EnXcdjW7L_91bH1_cwEVFg6M/edit?usp=drive_link)
- [Task Group Meeting Notes and Agenda](https://docs.google.com/document/d/1jIYTtfCPFzSKE_SBwK-nWv2BYpjAxocjbNNwleHSfuU/edit?usp=drive_link)

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
