### ISSUE TITLE
Y3: Task Group: Metadata workshop

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#127]
## Objective: 
- #15

## Tasks:
- #62 

## Deliverables:
- #77 
- #78 

## Steps to completion:
- [ ] Task group has followed [Procedures for Forming a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780045)
- [ ] Task group has read and followed [Procedures for Facilitating a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780532)
- [ ] Task(s) completed
- [ ] Deliverable(s) completed
- [ ] Reviewed by CWG committee (if applicable)
- [ ] Uploaded to Zenodo
- [ ] Blog and/or webinar
- [ ] Task group has read and followed [Procedures for Sunsetting a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245781023)

## Group Co-Leads and contact:
- John Chodacki, Zenodo

## Members and Repositories:
- Ana Van Gulick, Figshare
- David Scherer, Mendeley Data
- Steve Diggs, Zenodo

### For Awareness Only:
- Kelly Stathis @KellyStathis 
- Lisa Curtin @lcurtin  (Figshare)
- Traci Snowden @traciasnowden (Mendeley Data)
- Shanthi Keethdevan
- Nici Pfeiffer @nicipfeiffer 

## Resources:
- [Task Group SOP Template-DRAFT](https://docs.google.com/document/d/185S-hvjIysh-a1k7iZPSUWxjQ4kfXG2AapPZkIw7QH8/edit#heading=h.tyus4hcbugou)

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
