### ISSUE TITLE
Y3: Task Group: Resources (Best Practices, Data Curation, and DMP/DMSP)

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#131]
## Objective: 
- https://github.com/NIH-GREI/grei-pm/issues/15

## Task:
- https://github.com/NIH-GREI/grei-pm/issues/60

## Deliverables:
- https://github.com/NIH-GREI/grei-pm/issues/72
- https://github.com/NIH-GREI/grei-pm/issues/73
- https://github.com/NIH-GREI/grei-pm/issues/74

## Steps to completion:
- [x] Task group has followed [Procedures for Forming a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780045)
- [x] Task group has read and followed [Procedures for Facilitating a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780532)
- [ ] Task(s) completed
- [ ] Deliverable(s) completed
- [x] Reviewed by CWG committee (if applicable)
- [ ] Uploaded to Zenodo
- [ ] Blog and/or webinar
- [ ] Task group has read and followed [Procedures for Sunsetting a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245781023)

## Group Co-Leads and contact:
- Lisa Curtin @lcurtin (lisa@figshare.com) - Figshare
- Jess Herzog @jleighherzog (jherzog@datadryad.org) - Dryad 
- Ana Van Gulick @anavangulick (ana@figshare.com) - Figshare

## Members and Repositories:
- Maria Gould (DataCite)
- Julie Goldman (Dataverse)
- Lekshmi Sheelakumari (Mendeley Data)
- Crystal Steltenpohl (OSF)
- Daniel Steger (OSF)
- Sarah Sweet (Vivli)
- Sara Gonzales (Zenodo)
- John Chodacki (Zenodo)
- Steve Diggs (Zenodo)

### For awareness only
  - Matt Carson (Zenodo)
  - Josh Richardson (Zenodo)

## Resources:
- [SOP_TG-Resources-Checklist-DMP](https://docs.google.com/document/d/13AchoYpTLcruWaa6OMLyaL-xn8-GoXe-7icrOBK2lDc/edit?usp=sharing)

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
