### ISSUE TITLE
Y3: Task Group: AI taxonomy

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#136]
## Link to Deliverables (Zenodo): 
- [Chodacki, J., Hahnel, M., Iacus, S., Scherle, R., Olson, E., Pfeiffer, N., Holmes, K., & Hosseini, M. (2024). GREI Data Repository AI Taxonomy. arXiv.](https://doi.org/10.48550/arXiv.2411.08054) and on [Zenodo](https://zenodo.org/records/14201006)
## Objective: 
- #12 

## Tasks: 

- #95 

## Deliverables:

- #98 

## Steps to completion:
- [x] Task group has followed [Procedures for Forming a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780045)
- [x] Task group has read and followed [Procedures for Facilitating a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780532)
- [x] Task(s) completed
- [x] Deliverable(s) completed
- [x] Reviewed by CWG committee (if applicable)
- [x] Uploaded to Zenodo
- [x] Publish to a Journal
- [x] Blog and/or webinar
- [ ] Task group has read and followed [Procedures for Sunsetting a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245781023)

## Group Co-Leads and contact:
- Mark Hahnel @markhahnel (Figshare)
- John Chodacki (@chodacki) Zenodo/CDL

## Members and Repositories:
- Stefano Iacus (Dataverse)
- Ryan Scherle @ryscher  (Dryad)
- Sherif El Shamy (Mendeley Data)
- Eric Olson @eolson3 (OSF)
- Nici Pfeiffer @nicipfeiffer  (OSF)
- Kristi Holmes @kristiholmes (Zenodo)
- Mohammad Hosseini (Zenodo)

## Resources:

-[Task Group SOP Y3.V1.0](https://docs.google.com/document/d/185S-hvjIysh-a1k7iZPSUWxjQ4kfXG2AapPZkIw7QH8/edit#heading=h.tyus4hcbugou)
-*replace the link above with a link to the task group SOP

**Comment by chodacki** [comment]
> * Zenodo

journal/preprint server

**Comment by chodacki** [comment]
Final version of the document: https://docs.google.com/document/d/1xFoUPc5GSDskB2l9L2dKBfvP7rUsOOwTznx5zxZU2PY/edit?usp=sharing

**Comment by sbarbosadataverse** [comment]
@chodacki we can close this entire issue if sunsetting is complete. Please let me know. Thanks

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
