### ISSUE TITLE
Y3/Y4 TG: All GREI Metrics & Dashboard

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#139]
## Link to Deliverables (if public): 
Note* This is being combined with [Cross-GREI Metrics](https://github.com/NIH-GREI/grei-pm/issues/172)
Objective: Define Metrics & Explore Needs and Requirements of GREI, the NIH and the Community for dashboard visualization and implement

## Objective:
- #11 

## Tasks 
- #32
- #101 
- #103 
- #175
- #176
- #177 

## Deliverables:
- #106 

## Steps to completion:
- [ ] Task group has followed [Procedures for Forming a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780045)
- [ ] Task group has read and followed [Procedures for Facilitating a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780532)
- [ ] Task(s) completed
- [ ] Deliverable(s) completed
- [ ] Reviewed by CWG committee (if applicable)
- [ ] Uploaded to Zenodo
- [ ] Blog and/or webinar
- [ ] Task group has read and followed [Procedures for Sunsetting a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245781023)

## Group Co-Leads and contact:
- Tina Zdawczyk

## Members and Repositories:
- Maria Gould 
- Audrey Hamelers 
- Mark Hahnel @markhahnel (Figshare)
- Traci Snowden @traciasnowden (Mendeley Data)
- Eric Livingston (Mendeley Data)
- Eric Olson @eolson3 
- Brian Geiger
- Kristi Holmes @kristiholmes (Zenodo)

### For Awareness Only:
- Matt Buys @mjbuys (Datacite)
- Ana Van Gulick @anavangulick (Figshare)
- Ann Connolly 

## Resources:
- #11 
- [SOP for Task Groups](https://docs.google.com/document/d/1AzDnOMC6UptBUnGEc__Eh8SDhMwDfeo_Cp5Vewtxarc/edit#heading=h.tyus4hcbugou)
- [Task Group SOP Template-DRAFT](https://docs.google.com/document/d/185S-hvjIysh-a1k7iZPSUWxjQ4kfXG2AapPZkIw7QH8/edit#heading=h.tyus4hcbugou)

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
