### ISSUE TITLE
Y3: Task Group: Cross-repository search

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#140]
## Objective: 
- #10 

## Tasks 
- #23
- #24 
- #25 

## Deliverables:
- #28 
- #29 
- #30 

## Steps to completion:
- [x] Task group has followed [Procedures for Forming a Task Group](https://docs.google.com/document/d/185S-hvjIysh-a1k7iZPSUWxjQ4kfXG2AapPZkIw7QH8/edit#heading=h.9xgtx2akm4ow)
- [x] Task group has read and followed [Procedures for Facilitating a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780532)
- [ ] Task(s) completed
- [ ] Deliverable(s) completed
- [ ] Reviewed by CWG committee (if applicable)
- [ ] Uploaded to Zenodo
- [ ] Blog and/or webinar
- [ ] Task group has read and followed [Procedures for Sunsetting a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245781023)

## Group Co-Leads and contact:
- Traci Snowden @traciasnowden (t.snowden@elsevier.com) - Mendeley Data 

## Members and Repositories:
- Traci Snowden @traciasnowden  (Mendeley Data)
- Ryan Scherle @ryscher (Dryad)
- Mark Hahnel @markhahnel (Figshare)
- Tina Zdawczyk (Mendeley Data)
- Eric Livingston (Mendeley Data)
- Kristi Holmes @kristiholmes (Zenodo)
- Julian Gautier (Dataverse)

### For Awareness Only
- 

## Resources:
- [Task Group SOP Y3.V1.0](https://docs.google.com/document/d/1nnlqCGSiSJWwfYPp68UpOvpGkb5hS4t8OnuzT-AbxzY/edit)
- [Meeting Notes and Agenda](https://docs.google.com/document/d/1a2vcPejvhCTAXNODdB0NNrz5yrryyZgto8vDMneBgsU/edit?usp=sharing)
