### ISSUE TITLE
Y#-#: Task Group: Metadata Recommendations

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#144]
### Metadata Recommendation V2 (GREI Objective: Consistent Metadata)
- #8 

### Non-Data Object Linking (GREI Objective: Connecting Digital Objects)
- #53

### Data Citations (GREI Objective: Connecting Digital Objects)
- #54 

### Metadata Recommendation V2 (GREI Objective: Consistent Metadata)
- #18 

### Non-Data Object Linking (GREI Objective: Connecting Digital Objects)
- #56 

### Data Citations (GREI Objective: Connecting Digital Objects)
- #55 

## Steps to completion:
- [ ] Task group has followed [Procedures for Forming a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780045)
- [ ] Task group has read and followed [Procedures for Facilitating a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780532)
- [ ] Task(s) completed
- [ ] Deliverable(s) completed
- [ ] Reviewed by CWG committee (if applicable)
- [ ] Uploaded to Zenodo
- [ ] Blog and/or webinar
- [ ] Task group has read and followed [Procedures for Sunsetting a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245781023)

## Group Co-Leads and contact:

- David Scherer (Mendeley Data)

## Members and Repositories:
- David Scherer (Mendeley Data)
- Julian Gautier (Dataverse)
- Kelly Stathis @KellyStathis 
- Audrey Hamelers (Dryad)
- Ana Van Gulick @anavangulick (Figshare)
- Eric Olson @eolson3  (OSF)
- Gretchen Gueguen (OSF)
- Kristi Holmes @kristiholmes (Zenodo)

### For awareness only:
- Lisa Curtin @lcurtin (Figshare)
- Eric Livingston (Mendeley Data)
- Lars Holm Nielsen @lnielsen 
- Steve Diggs @sdiggs 

## Resources:
- [Task Group SOP Y3.V1.0](https://docs.google.com/document/d/185S-hvjIysh-a1k7iZPSUWxjQ4kfXG2AapPZkIw7QH8/edit#heading=h.tyus4hcbugou)
-*replace the link above with a link to the task group SOP

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
