### ISSUE TITLE
Revision to GREI Code of Conduct

### ISSUE THREAD

**Issue by lekshmi-sheelakumari** [NIH-GREI/grei-pm#146]
## Objectives 
Update the [NIH GREI Coopetition CWG Principles and Code of Conduct - Updated August 2023](https://docs.google.com/document/d/1uDy6zekV1WDNh0YiPIBTunHQhIt0oOIYY0OefA1qh74/edit#heading=h.9olwn616ds3w)

## Tasks

- [x] Email Code of Conduct
- [x] Discuss in the next Co-Chair meeting
- [x] DRAFT review with Ishwar, 
- [x] get it ready to present at July CWG meeting 
- [ ] Discuss in Aug CWG meeting if team members have any questions 

## Resources
[NIH GREI Coopetition CWG Principles and Code of Conduct - Updated August 2023](https://docs.google.com/document/d/1uDy6zekV1WDNh0YiPIBTunHQhIt0oOIYY0OefA1qh74/edit#heading=h.9olwn616ds3w)

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
