### ISSUE TITLE
Updating Show and Tell Decks (June Update)

### ISSUE THREAD

**Issue by lekshmi-sheelakumari** [NIH-GREI/grei-pm#147]
## Objective
Each Repository to add the [Y3 Show & Tell Decks](https://drive.google.com/drive/u/1/folders/1jdKB1CfnTwuV1zdaiHwkB674EJe-bZQi) with any new updates they have done after the last update. 

## Tasks

- [x] Share the updated [Y3 Show & Tell Deck Template ](https://docs.google.com/presentation/d/1X715H9p3YDNITbtDBa2LsU1QGj_0KJ3MeoPeiwfggaM/edit?usp=drive_link)
- [x] Updated message to teams clarifying what updates to add
- [x] Kristi to make updates to the templates. 
- [x] Send out the templates and discuss in the next CWG meeting. 
- [ ] Teams to update the Y3 Show & Tell Decks (Before 21 Aug)
- [ ] Qns to be addressed during Aug CWG meeting 
- [ ] Repositories to discuss if they are comfortable with the decks being public. 

## Resources

- [Y3 Show & Tell Deck Template ](https://docs.google.com/presentation/d/1X715H9p3YDNITbtDBa2LsU1QGj_0KJ3MeoPeiwfggaM/edit?usp=drive_link)
- [Y3 Show & Tell Decks](https://drive.google.com/drive/u/1/folders/1jdKB1CfnTwuV1zdaiHwkB674EJe-bZQi) with any new updates they have done after the last update

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
