### ISSUE TITLE
Y3: Task Group: Metadata Issues

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#152]
## Objective: 
- https://github.com/NIH-GREI/grei-pm/issues/7

## Task
- https://github.com/NIH-GREI/grei-pm/issues/9

### File Level Metadata
- [x] #21
- [x] #31

### Schema.org
- [x] #19 

### Contributor Roles Assessment
- [x] #20

## Steps to completion:
- [x] Task group has followed [Procedures for Forming a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780045)
- [x] Task group has read and followed [Procedures for Facilitating a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780532)
- [ ] Task(s) completed
- [ ] Deliverable(s) completed
- [ ] Reviewed by CWG committee (if applicable)
- [ ] Uploaded to Zenodo
- [ ] Blog and/or webinar
- [ ] Task group has read and followed [Procedures for Sunsetting a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245781023)

## Group Co-leads and contact:
- Mark Hahnel, @markhahnel (m.hahnel@digital-science.com) - Figshare
- Steve Diggs, @sdiggs (steve.diggs@ucop.edu) - UCOP/Zenodo

## Members and Repositories
- Julian Gautier (Harvard Dataverse)
- Matt Buys (DataCite)
- Audrey Hamelers (Dryad)
- Traci Snowden (Mendeley Data)
- Eric Olson (OSF)
- Gretchen Gueguen (OSF)
- Lars Holm Nielsen (Zenodo)
- Kristi Holmes (Zenodo)

### For Awareness Only
- Kelly Stathis (DataCite)
- Ana Van Gulick (Figshare)
- Luca Belletti (Mendeley Data)
- Eric Livingston (Mendeley Data)

## Resources
- [Task Group SOP Y3.V1.0](https://docs.google.com/document/d/185S-hvjIysh-a1k7iZPSUWxjQ4kfXG2AapPZkIw7QH8/edit#heading=h.tyus4hcbugou)
- *replace the link above with the  established SOP for the task group

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
