### ISSUE TITLE
Y3-4: Task Group: Github PM

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#158]
## Link to Deliverables in Zenodo and Blog:
- [Blog](https://medium.com/@blog-grei/unlocking-innovation-the-generalist-repositories-embrace-transparency-and-community-on-github-08cdef676e2e)
-

## Objective:
- This Task Group manages and monitors the NIH-GREI Github repository. It plays a critical role in task group management and facilitation, bringing transparency to GREI tasks and deliverables.

## Tasks:
- [ ] Enter accepted yearly proposed goals into GREI Github (Y1-4)
- [ ] Facilitate Task Group SOP

## Deliverables:

- [ ] Add approved yearly plan to Github y1, y2, y3
- [ ] QA Task Groups and related issues for 
  - [ ] Tasks
  - [ ] Deliverables 
  - [ ] Labels
  - [ ] Milestones
  - [ ] Status

## Steps to completion:
- [ ] Task group has followed [Procedures for Forming a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780045)
- [ ] Task group has read and followed [Procedures for Facilitating a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780532)
- [ ] Task(s) completed
- [ ] Deliverable(s) completed
- [ ] Reviewed by CWG committee (if applicable)
- [ ] Uploaded to Zenodo
- [x] Blog and/or webinar
- [ ] Task group has read and followed [Procedures for Sunsetting a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245781023)

## Group Co-Leads and contact:
- Sonia Barbosa @sbarbosadataverse 
- Lekshmi Sheelakumari @lekshmi-sheelakumari 
- Lisa Curtin @lcurtin 
- Pearl Go @pg05 
- Traci Snowden @traciasnowden 
- Matt Ryan @ryscher 
- Matt Carson @carsonicator 
- Sarah Gonzales @saragon02 
- Sara Sweet @ssweetVivli 

## Related
- Task Group: GitHub SOP

## Resources
-

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
