### ISSUE TITLE
Y1-4: Task Group: Resources - Comparison Chart

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#36]
## Objective: 
- https://github.com/NIH-GREI/grei-pm/issues/1

## Tasks 
- #2 
- #3 

## Deliverables
-  #4 

- [x] Asked GR repositories to review this [internal spreadsheet](https://docs.google.com/spreadsheets/d/1wZFX748SNd5Bh5P-WNJhVENuUXxD8Jf3bTUy0LsNGyo/edit?gid=1413020762#gid=1413020762)
- [x] non-GREI review internal spreadsheet:(https://docs.google.com/spreadsheets/d/1wZFX748SNd5Bh5P-WNJhVENuUXxD8Jf3bTUy0LsNGyo/edit?gid=1413020762#gid=1413020762), [google survey used](https://docs.google.com/forms/d/1zJhWSKyypmTYv31UFja58KyzN3a33DvfPVY1BCEnNm4/edit)

- #5 
- #6 

## Steps to completion:
- [x] Task group has followed [Procedures for Forming a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780045)
- [x] Task group has read and followed [Procedures for Facilitating a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245780532)
- [ ] Task(s) completed
- [ ] Deliverable(s) completed
- [ ] Reviewed by CWG committee (if applicable)
- [ ] Uploaded to Zenodo
- [ ] Blog and/or webinar
- [ ] Task group has read and followed [Procedures for Sunsetting a Task Group](https://github.com/NIH-GREI/grei-pm/issues/34#issuecomment-2245781023)

## Group Co-Leads and contact:
- Sonia Barbosa: sbarbosa@g.harvard.edu, @sbarbosadataverse
- Matt Carson: matthew.carson@northwestern.edu, @carsonicator  

## Members and Repositories:
- Sonia Barbosa @sbarbosadataverse (Dataverse)
- Matt Carson @carsonicator (Zenodo)
- Sara Gonzales @saragon02 (Zenodo)
- Lisa Curtin: @lcurtin (Figshare)
- Ana Van Gulick @anavangulick (Figshare)
- Eric Olson @eolson3 (OSF)
- Jess Herzog @jleighherzog (Dryad)
- Traci Snowden @traciasnowden (Mendeley Data)
- Sarah Sweet @ssweetVivli (Vivli)

## Resources
- [Link to GREI Objective 1 issue](https://github.com/NIH-GREI/grei-pm/issues/1)
- [Task Group SOP Y3.V1.0](https://docs.google.com/document/d/185S-hvjIysh-a1k7iZPSUWxjQ4kfXG2AapPZkIw7QH8/edit#heading=h.tyus4hcbugou)

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
