### ISSUE TITLE
Y3: In-person meeting tasks and deliverable

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#81]
## Date and Location
Dates: 19, 20 Sep, 2024
Location: MATTER, 222 W Merchandise Mart Plaza #1230, Chicago, IL 60654, United States
[Google Maps Link](https://www.google.com/maps/place/MATTER/@41.8881092,-87.6537485,15z/data=!4m7!3m6!1s0x880e2cb6fc9e61a9:0xa9bd14b20fd69cc7!4b1!8m2!3d41.8880947!4d-87.6352945!16s%2Fg%2F11b81rprbc?entry=ttu)

## Tasks

- [ ] Prepare Agenda
- [ ] Ensure all Task groups are up to date with activity and progress in Git
- [ ] Develop a report on Task group progress to present
- [ ] Consider a planning meeting with the " Council Working Group" - Like remote since they won't attend the face to face

## Resources

- [Year 3 in-person meeting details](https://drive.google.com/drive/folders/1JJL5r5KyUpunvzgyJjWCtm4aepz_ZtWE)
- [Registration Sheet](https://docs.google.com/spreadsheets/d/1IUzKMi6OumTsU9eNECJEmNiPRxN3QSk_s3unPPW_y4Q/edit?gid=1930596124#gid=1930596124)
- [Helpful Details](https://docs.google.com/document/d/1H-cDMw27tiKd0l78E3jr64AKvWkdcFp2PXsGcsCDwa8/edit)

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
