### ISSUE TITLE
Y3: Task-Group SOP Template Review

### ISSUE THREAD

**Issue by sbarbosadataverse** [NIH-GREI/grei-pm#82]
### Tasks

- [x] Finalise the [Task Group SOP Template-DRAFT](https://docs.google.com/document/d/185S-hvjIysh-a1k7iZPSUWxjQ4kfXG2AapPZkIw7QH8/edit#heading=h.tyus4hcbugou)
- [x] Link to the SOP template to be added to the GitHub issues for Task Groups 
- [x] Respond to the qns and comments in the SOP
- [x] Align the updated SOP with Co-Chairs 
- [ ] Present in the CWG Meeting
- [ ] Teams to start using the SOP for forming task groups in Q2 and V1.1 of SOP to be published with feedback 

## #Draft Link:
- [SOP for Task Groups](https://docs.google.com/document/d/1AzDnOMC6UptBUnGEc__Eh8SDhMwDfeo_Cp5Vewtxarc/edit#heading=h.tyus4hcbugou)
- [Task Group SOP Template-DRAFT](https://docs.google.com/document/d/185S-hvjIysh-a1k7iZPSUWxjQ4kfXG2AapPZkIw7QH8/edit#heading=h.tyus4hcbugou)

**Comment by DerekJones1987** [comment]
This issue was closed in March 2025 as part of a process to simplify the GREI GitHub for use as a tool for public transparency and community feedback. The closed status does not indicate that the content described in this issue was completed at time of closing.
